# Generated by Django 3.0.8 on 2020-07-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
